"""Shared data contract for the pipeline.

Monetary values are Decimal everywhere. They are never floats: 0.1 + 0.2 != 0.3 in
binary floating point, and a cent of drift in a reconciliation check is the difference
between a receipt passing and failing validation.
"""

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class FieldStatus(str, Enum):
    """Three outcomes, not two.

    Abstaining is safe; inventing a value is dangerous. A metric that scores them
    identically is measuring the wrong thing.
    """

    CORRECT = "correct"
    INCORRECT = "incorrect"
    ABSTAINED = "abstained"


class Provenance(BaseModel):
    """Where in the source document a value came from."""

    page: int = 0
    bbox: Optional[tuple[float, float, float, float]] = None
    source_text: Optional[str] = None


class ExtractedField(BaseModel):
    value: Optional[str] = None
    confidence: float = 0.0
    provenance: Optional[Provenance] = None

    @property
    def abstained(self) -> bool:
        return self.value is None


class LineItem(BaseModel):
    name: Optional[str] = None
    quantity: Decimal = Decimal("1")
    unit_price: Optional[Decimal] = None
    total_price: Optional[Decimal] = None


class ExtractedReceipt(BaseModel):
    """Structured output of the extraction step."""

    doc_id: str
    merchant: Optional[str] = None
    date: Optional[str] = None
    line_items: list[LineItem] = Field(default_factory=list)
    subtotal: Optional[Decimal] = None
    tax: Optional[Decimal] = None
    service_charge: Optional[Decimal] = None
    discount: Optional[Decimal] = None
    total: Optional[Decimal] = None

    field_confidences: dict[str, float] = Field(default_factory=dict)
    provenance: dict[str, Provenance] = Field(default_factory=dict)

    @property
    def min_confidence(self) -> float:
        return min(self.field_confidences.values(), default=0.0)

    @property
    def mean_confidence(self) -> float:
        vals = list(self.field_confidences.values())
        return sum(vals) / len(vals) if vals else 0.0

    def missing_fields(self) -> list[str]:
        core = ["merchant", "date", "total"]
        return [f for f in core if getattr(self, f) is None]


class Severity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"


class Finding(BaseModel):
    """A structured result from a deterministic check.

    Findings are emitted by code, never generated by a model. The routing decision is
    computed from these objects, so a model cannot introduce an unsupported claim into
    the decision path.
    """

    check_id: str
    passed: bool
    severity: Severity = Severity.INFO
    message: str = ""
    computed: dict[str, str] = Field(default_factory=dict)
    evidence_refs: list[str] = Field(default_factory=list)


class ReviewDecision(BaseModel):
    review_required: bool
    priority: float = 0.0
    reasons: list[str] = Field(default_factory=list)


class AnalysisResult(BaseModel):
    """What POST /analyze returns."""

    doc_id: str
    extraction: ExtractedReceipt
    findings: list[Finding] = Field(default_factory=list)
    decision: ReviewDecision
